### ISSUE TITLE
关于appToken的获取

### ISSUE THREAD

**Issue by Ryanmon** [dfvips/mddparser#1]
大神请问appToken是不是要抓加载视频的接口，好像app是做了cert pinning，没法直接抓到。其他普通的接口又没找到这个参数,求教。

**Comment by dfvips** [comment]
是的。需要抓接口。iphone使用stream是可以抓的，安卓用小黄鸟，root权限把证书放到系统去，就可以抓了。

**Comment by Ryanmon** [comment]
谢谢，用stream抓到了，之前用charles没成功，原来是没有在系统设置里面信任证书😓

**Comment by dfvips** [comment]
嗯嗯。
