### ISSUE TITLE
很多只能解析试看的几分钟视频了

### ISSUE THREAD

**Issue by bupbedepxinh** [dfvips/mddparser#5]
是我哪里设置不对吗

**Comment by dfvips** [comment]
appToken没有修改成会员的就只能看免费的部分，vip只能试看。

**Comment by bupbedepxinh** [comment]
是会员啊apptoken和ua都改了，有些能完全解析 有些能解析几集，有些一集也解析不了

**Comment by dfvips** [comment]
需要改App版本号，如果还这样只能说明你过度使用，或者是vip的token有问题。目前我这边测试使用没问题。
