### ISSUE TITLE
大神 M3U8解析出来的地址没办法下载

### ISSUE THREAD

**Issue by ericman0392** [dfvips/mddparser#6]
大神 M3U8解析出来的地址没办法下载，自定义了UA也不行 ，可以留个联系方式请教下您吗

**Comment by dfvips** [comment]
UA的问题，抓包一下手机端UA，下载的时候携带UA请求。

**Comment by ericman0392** [comment]
用你说的Simple GUI这个下载器请求头填上了的 Mdd/4.3.20 (ios 14.4)  下载 提示 地址无效  之前MP4版本我用IDM也是用的这个UA就可以下载

**Comment by dfvips** [comment]
你可以使用旧版本继续下载mp4。另外，地址无效是UA问题，无法直接提供，因为提供就会被封。抓包一下手机端UA。

**Comment by ericman0392** [comment]
![webwxgetmsgimg2](https://user-images.githubusercontent.com/103084356/164760450-a55b3be2-1391-4459-b89a-409ac92cf729.jpg)
我抓的这个 Mdd/4.3.20 (ios 14.4) 不对的吗  可以教教我吗有偿

**Comment by dfvips** [comment]
签名算法是安卓的，配合安卓的UA。

**Comment by dfvips** [comment]
![image](https://user-images.githubusercontent.com/21048630/164761426-783caaad-ae6f-4b0a-8b11-a25d5b1084d5.png)
另外，我这边测试正常，你看看是不是你改错了什么。

**Comment by ericman0392** [comment]
好的  我在试试  谢谢您
