### ISSUE TITLE
请问短信验证方式怎么找token?

### ISSUE THREAD

**Issue by huanzhiyi** [dfvips/mddparser#7]
只能短信验证

**Comment by dfvips** [comment]
手机端抓包播放页面，可以看到token的。目前 ios https协议已经不支持抓包，建议安卓Root设备尝试。至于怎么抓包，可以参考网上的教程。

**Comment by huanzhiyi** [comment]
感谢您的来信！

**Comment by huanzhiyi** [comment]
> 手机端抓包播放页面，可以看到token的。目前 ios https协议已经不支持抓包，建议安卓Root设备尝试。至于怎么抓包，可以参考网上的教程。

嗯 好的 感谢 再请教一个问题，请问是否知道一般token有效多长时间 ？ 感觉变得挺快的

**Comment by dfvips** [comment]
不太清楚，但是一般一个月内是没问题的。

**Comment by huanzhiyi** [comment]
> 不太清楚，但是一般一个月内是没问题的。

明白，感谢解答
